name: tests

on:
  push:
    branches: [main, develop]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-test-image:
    name: Build Test Image
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.image_name.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image name and tag
        id: image_name
        run: echo "name=ghcr.io/${{ github.repository_owner,, }}/newsdom-api/test:${{ github.sha }}" | tee -a $GITHUB_OUTPUT

      - name: Build and push test image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.test
          push: true
          tags: ${{ steps.image_name.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  pytest:
    name: Run Pytest in Container
    runs-on: ubuntu-latest
    needs: build-test-image
    container:
      image: ${{ needs.build-test-image.outputs.image_name }}
    env:
      PYTHONWARNINGS: error
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: uv run pytest
